### PR TITLE
Recorded Future Sandbox: Bugfix - Fix the freezing/hanging of report fetching.

### PR DESCRIPTION
**Pull request by simon-hornestedt-rf**
## Pull Request Checklist

- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations 
- [x] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
    - No new cryptographic modules.
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
    - Not added file system usage.

## Release Notes

This code change fixes frozen report fetching tasks. The frozen tasks were caused by a failed data insertions in PostgreSQL.
The failed insertion was caused by the JSON containing unicode null bytes. 
The change adds code that strips (unicode) null bytes from report before parsing it with JSON parser.

---
Thanks for contributing!

### CODE REVIEW

**Comment by dvora-crest** [comment]
Hello @recordedfuture-simonhornestedt,
As per the standard practices, min_phantom_version should be 6.0.0, could you please test this app on 6.0.0 and update the min_phantom_version in json?
Also, we have stopped explicitly adding dependency for requests module , so could you please remove it from requirements.txt?
Thanks!

**Comment by simon-hornestedt-rf** [comment]
> Hello @recordedfuture-simonhornestedt, As per the standard practices, min_phantom_version should be 6.0.0, could you please test this app on 6.0.0 and update the min_phantom_version in json? Also, we have stopped explicitly adding dependency for requests module , so could you please remove it from requirements.txt? Thanks!

Updated!

**Comment by dvora-crest** [comment]
Hello @recordedfuture-simonhornestedt,
As per the standard practices, minor version of app should be updated in case of bug fix. So could you please update the minor version of the app?

**Comment by simon-hornestedt-rf** [comment]
@dvora-crest App version bumped as requested

**Review by mmomin-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Review by pdesai-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
